# Build and Release OpenWrt UDPBD Server IPK (Minimal)
name: Build and Release OpenWrt UDPBD IPK

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    strategy:
      matrix:
        target:
          - {
              version: "19.07.9",
              arch: "ramips",
              subarch: "mt76x8",
              pkg_arch: "mipsel_24kc",
            }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 2.x
        run: |
          sudo apt-get update
          sudo apt-get install -y python2
          # Create symlink so 'python' command works
          sudo ln -sf /usr/bin/python2 /usr/bin/python
          python --version

      - name: Download and setup OpenWrt SDK
        run: |
          cd ..
          SDK_VERSION=${{ matrix.target.version }}
          SDK_ARCH=${{ matrix.target.arch }}
          SDK_SUBARCH=${{ matrix.target.subarch }}

          case ${SDK_VERSION} in
            19.07.*) GCC_VERSION="7.5.0" ;;
            22.03.*) GCC_VERSION="11.2.0" ;;
            23.05.*) GCC_VERSION="12.3.0" ;;
            *) GCC_VERSION="7.5.0" ;;
          esac

          SDK_URL="https://downloads.openwrt.org/releases/${SDK_VERSION}/targets/${SDK_ARCH}/${SDK_SUBARCH}/openwrt-sdk-${SDK_VERSION}-${SDK_ARCH}-${SDK_SUBARCH}_gcc-${GCC_VERSION}_musl.Linux-x86_64.tar.xz"
          echo "Downloading SDK from ${SDK_URL}"
          wget -q ${SDK_URL} -O openwrt-sdk.tar.xz
          tar -xf openwrt-sdk.tar.xz
          mv openwrt-sdk-* openwrt-sdk
          echo "WORK_DIR=$(pwd)/openwrt-sdk" >> $GITHUB_ENV

      - name: Install package sources into SDK
        run: |
          mkdir -p ${{ env.WORK_DIR }}/package/udpbd-server
          cp -r $GITHUB_WORKSPACE/* ${{ env.WORK_DIR }}/package/udpbd-server/

      - name: Compile the package (No feeds update)
        id: compile
        run: |
          cd ${{ env.WORK_DIR }}

          # Skip feed updates - use what's in the SDK
          echo "Skipping feed updates due to server issues..."

          # Basic configuration
          make defconfig

          # Compile UDPBD server package directly
          make package/udpbd-server/compile V=s

          # Find the generated IPK file
          IPK_PATH=$(find bin/packages -type f -name "udpbd-server_*.ipk")
          echo "Found IPK: ${IPK_PATH}"
          echo "ipk_path=${IPK_PATH}" >> $GITHUB_OUTPUT

      - name: Upload IPK as artifact
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v4
        with:
          name: udpbd-server-ipk-${{ matrix.target.version }}-${{ matrix.target.pkg_arch }}
          path: ${{ env.WORK_DIR }}/${{ steps.compile.outputs.ipk_path }}

      - name: Create GitHub Release and Upload Asset
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ env.WORK_DIR }}/${{ steps.compile.outputs.ipk_path }}
          tag_name: ${{ github.ref_name }}
          name: UDPBD Server ${{ github.ref_name }}
          body: |
            ## OpenWrt UDPBD Server Release ${{ github.ref_name }}

            Cross-compiled IPK packages for OpenWrt targets.

            ### Installation:
            ```bash
            scp udpbd-server_*.ipk root@your-router:/tmp/
            opkg install /tmp/udpbd-server_*.ipk
            udpbd-server /dev/sda1
            ```

            Built from commit: ${{ github.sha }}
          draft: false
          prerelease: false
