# Build and Release OpenWrt UDPBD Server IPK
name: Build and Release OpenWrt UDPBD IPK

# Trigger on version tags
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    strategy:
      matrix:
        # OpenWrt SDK targets - add more as needed
        target:
          - {
              version: "19.07.9",
              arch: "ramips",
              subarch: "mt76x8",
              pkg_arch: "mipsel_24kc",
            }
          - {
              version: "22.03.5",
              arch: "ramips",
              subarch: "mt7621",
              pkg_arch: "mipsel_24kc",
            }
          - {
              version: "23.05.3",
              arch: "ramips",
              subarch: "mt76x8",
              pkg_arch: "mipsel_24kc",
            }
          # Add more targets:
          # - { version: "22.03.5", arch: "ath79", subarch: "generic", pkg_arch: "mips_24kc" }
          # - { version: "22.03.5", arch: "mediatek", subarch: "mt7622", pkg_arch: "aarch64_cortex-a53" }

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python 2.x for older OpenWrt versions
      - name: Install Python 2.x
        run: |
          sudo apt-get update
          sudo apt-get install -y python2

      # Download and setup OpenWrt SDK
      - name: Download and setup OpenWrt SDK
        run: |
          cd ..
          SDK_VERSION=${{ matrix.target.version }}
          SDK_ARCH=${{ matrix.target.arch }}
          SDK_SUBARCH=${{ matrix.target.subarch }}

          # Determine GCC version based on OpenWrt version
          case ${SDK_VERSION} in
            19.07.*) GCC_VERSION="7.5.0" ;;
            22.03.*) GCC_VERSION="11.2.0" ;;
            23.05.*) GCC_VERSION="12.3.0" ;;
            *) GCC_VERSION="7.5.0" ;;
          esac

          SDK_URL="https://downloads.openwrt.org/releases/${SDK_VERSION}/targets/${SDK_ARCH}/${SDK_SUBARCH}/openwrt-sdk-${SDK_VERSION}-${SDK_ARCH}-${SDK_SUBARCH}_gcc-${GCC_VERSION}_musl.Linux-x86_64.tar.xz"
          echo "Downloading SDK from ${SDK_URL}"
          wget -q ${SDK_URL} -O openwrt-sdk.tar.xz
          tar -xf openwrt-sdk.tar.xz
          mv openwrt-sdk-* openwrt-sdk
          echo "WORK_DIR=$(pwd)/openwrt-sdk" >> $GITHUB_ENV

      # Copy package sources to SDK
      - name: Install package sources into SDK
        run: |
          mkdir -p ${{ env.WORK_DIR }}/package/udpbd-server
          cp -r $GITHUB_WORKSPACE/* ${{ env.WORK_DIR }}/package/udpbd-server/

      # Compile the package
      - name: Compile the package
        id: compile
        run: |
          cd ${{ env.WORK_DIR }}

          # Update feeds
          ./scripts/feeds update
          ./scripts/feeds install

          # Install C++ standard library dependency
          ./scripts/feeds install libstdcpp
          echo "CONFIG_PACKAGE_libstdcpp=y" >> .config

          # Build configuration
          make defconfig

          # Compile UDPBD server package
          make package/udpbd-server/compile V=s

          # Find the generated IPK file
          IPK_PATH=$(find bin/packages -type f -name "udpbd-server_*.ipk")
          echo "Found IPK: ${IPK_PATH}"
          echo "ipk_path=${IPK_PATH}" >> $GITHUB_OUTPUT

      # Upload as artifact for non-release builds
      - name: Upload IPK as artifact
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v4
        with:
          name: udpbd-server-ipk-${{ matrix.target.version }}-${{ matrix.target.pkg_arch }}
          path: ${{ env.WORK_DIR }}/${{ steps.compile.outputs.ipk_path }}

      # Create GitHub release and upload IPK
      - name: Create GitHub Release and Upload Asset
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ env.WORK_DIR }}/${{ steps.compile.outputs.ipk_path }}
          tag_name: ${{ github.ref_name }}
          name: UDPBD Server ${{ github.ref_name }}
          body: |
            ## OpenWrt UDPBD Server Release ${{ github.ref_name }}

            Cross-compiled IPK packages for various OpenWrt targets.

            ### Installation:
            ```bash
            # Copy IPK to your OpenWrt device
            scp udpbd-server_*.ipk root@your-router:/tmp/

            # Install on OpenWrt
            opkg install /tmp/udpbd-server_*.ipk

            # Run manually
            udpbd-server /dev/sda1

            # Or configure as service
            /etc/init.d/udpbd-server enable
            /etc/init.d/udpbd-server start
            ```

            ### Compatible with:
            - PS2 with UDPBD-enabled OPL
            - Network block device clients

            Built from commit: ${{ github.sha }}
          draft: false
          prerelease: false
